### ISSUE TITLE
Feature request: Grab changelog from github releases

### ISSUE THREAD

**Issue by jwalton** [JCofman/Changelog#4]
Hey, love this project - it's super slick.  But I have a feature request for you; it would be nice if, in addition to changelog.md, this also supported fetching the changelog from github releases (for example, from my project [exegesis](https://github.com/exegesis-js/exegesis/releases)).  This is where [semantic-release](https://github.com/semantic-release/semantic-release) puts changelogs by default, and most big projects seem to put release notes here.

**Comment by JCofman** [comment]
Hi @jwalton thank you very much 😄. Sorry I just implemented a dummy way to verify whether the releases have some valid content to show in the tooltip I just checked the first release on some change notes. 

Since your mentioned [exegesis](https://github.com/exegesis-js/exegesis/releases) project didn't provide any notes on the first release the extension omitted the requests to the GitHub API. A lot of packages use semantic-releases but don't provide any information about the changes they made, so I tried to avoid to add those to the tooltip.

I hope this is fixed in the newest release of this extension.

Please also be aware that the GitHub API has a really low limit on unauthenticated requests 😢 after 60 requests you have to wait one hour to get valid tooltip information from the `https://developer.github.com/v3/repos/releases/` API.
